import { ChipsAutocompleteExample } from './chips-autocomplete/chips-autocomplete-example';
import { ChipsDragDropExample } from './chips-drag-drop/chips-drag-drop-example';
import { ChipsInputExample } from './chips-input/chips-input-example';
import { ChipsOverviewExample } from './chips-overview/chips-overview-example';
import { ChipsStackedExample } from './chips-stacked/chips-stacked-example';
import { ChipsHarnessExample } from './chips-harness/chips-harness-example';
import { ChipsFormControlExample } from './chips-form-control/chips-form-control-example';
import { ChipsAvatarExample } from './chips-avatar/chips-avatar-example';
import * as i0 from "@angular/core";
import * as i1 from "./chips-autocomplete/chips-autocomplete-example";
import * as i2 from "./chips-drag-drop/chips-drag-drop-example";
import * as i3 from "./chips-input/chips-input-example";
import * as i4 from "./chips-overview/chips-overview-example";
import * as i5 from "./chips-stacked/chips-stacked-example";
import * as i6 from "./chips-harness/chips-harness-example";
import * as i7 from "./chips-form-control/chips-form-control-example";
import * as i8 from "./chips-avatar/chips-avatar-example";
import * as i9 from "@angular/common";
import * as i10 from "@angular/cdk/drag-drop";
import * as i11 from "@angular/material/autocomplete";
import * as i12 from "@angular/material/button";
import * as i13 from "@angular/material/chips";
import * as i14 from "@angular/material/icon";
import * as i15 from "@angular/material/form-field";
import * as i16 from "@angular/forms";
export { ChipsAutocompleteExample, ChipsDragDropExample, ChipsInputExample, ChipsOverviewExample, ChipsStackedExample, ChipsHarnessExample, ChipsFormControlExample, ChipsAvatarExample, };
export declare class ChipsExamplesModule {
    static ɵfac: i0.ɵɵFactoryDeclaration<ChipsExamplesModule, never>;
    static ɵmod: i0.ɵɵNgModuleDeclaration<ChipsExamplesModule, [typeof i1.ChipsAutocompleteExample, typeof i2.ChipsDragDropExample, typeof i3.ChipsInputExample, typeof i4.ChipsOverviewExample, typeof i5.ChipsStackedExample, typeof i6.ChipsHarnessExample, typeof i7.ChipsFormControlExample, typeof i8.ChipsAvatarExample], [typeof i9.CommonModule, typeof i10.DragDropModule, typeof i11.MatAutocompleteModule, typeof i12.MatButtonModule, typeof i13.MatChipsModule, typeof i14.MatIconModule, typeof i15.MatFormFieldModule, typeof i16.ReactiveFormsModule], [typeof i1.ChipsAutocompleteExample, typeof i2.ChipsDragDropExample, typeof i3.ChipsInputExample, typeof i4.ChipsOverviewExample, typeof i5.ChipsStackedExample, typeof i6.ChipsHarnessExample, typeof i7.ChipsFormControlExample, typeof i8.ChipsAvatarExample]>;
    static ɵinj: i0.ɵɵInjectorDeclaration<ChipsExamplesModule>;
}
