import * as i0 from '@angular/core';
import { Component } from '@angular/core';
import * as i1 from '@angular/cdk/accordion';
import { CdkAccordionModule } from '@angular/cdk/accordion';

/**
 * @title Accordion overview
 */
class CdkAccordionOverviewExample {
    constructor() {
        this.items = ['Item 1', 'Item 2', 'Item 3', 'Item 4', 'Item 5'];
        this.expandedIndex = 0;
    }
    static { this.ɵfac = i0.ɵɵngDeclareFactory({ minVersion: "12.0.0", version: "17.2.0-rc.1", ngImport: i0, type: CdkAccordionOverviewExample, deps: [], target: i0.ɵɵFactoryTarget.Component }); }
    static { this.ɵcmp = i0.ɵɵngDeclareComponent({ minVersion: "17.0.0", version: "17.2.0-rc.1", type: CdkAccordionOverviewExample, isStandalone: true, selector: "cdk-accordion-overview-example", ngImport: i0, template: "<cdk-accordion class=\"example-accordion\">\n  @for (item of items; track item; let index = $index) {\n    <cdk-accordion-item\n\n      #accordionItem=\"cdkAccordionItem\"\n      class=\"example-accordion-item\"\n      role=\"button\"\n      tabindex=\"0\"\n      [attr.id]=\"'accordion-header-' + index\"\n      [attr.aria-expanded]=\"accordionItem.expanded\"\n      [attr.aria-controls]=\"'accordion-body-' + index\">\n      <div class=\"example-accordion-item-header\" (click)=\"accordionItem.toggle()\">\n        {{ item }}\n        <span class=\"example-accordion-item-description\">\n          Click to {{ accordionItem.expanded ? 'close' : 'open' }}\n        </span>\n      </div>\n      <div\n        class=\"example-accordion-item-body\"\n        role=\"region\"\n        [style.display]=\"accordionItem.expanded ? '' : 'none'\"\n        [attr.id]=\"'accordion-body-' + index\"\n        [attr.aria-labelledby]=\"'accordion-header-' + index\">\n        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perferendis\n        excepturi incidunt ipsum deleniti labore, tempore non nam doloribus blanditiis\n        veritatis illo autem iure aliquid ullam rem tenetur deserunt velit culpa?\n      </div>\n    </cdk-accordion-item>\n  }\n</cdk-accordion>\n\n", styles: [".example-accordion {\n  display: block;\n  max-width: 500px;\n}\n\n.example-accordion-item {\n  display: block;\n  border: solid 1px #ccc;\n}\n\n.example-accordion-item + .example-accordion-item {\n  border-top: none;\n}\n\n.example-accordion-item-header {\n  display: flex;\n  align-content: center;\n  justify-content: space-between;\n}\n\n.example-accordion-item-description {\n  font-size: 0.85em;\n  color: #999;\n}\n\n.example-accordion-item-header,\n.example-accordion-item-body {\n  padding: 16px;\n}\n\n.example-accordion-item-header:hover {\n  cursor: pointer;\n  background-color: #eee;\n}\n\n.example-accordion-item:first-child {\n  border-top-left-radius: 4px;\n  border-top-right-radius: 4px;\n}\n\n.example-accordion-item:last-child {\n  border-bottom-left-radius: 4px;\n  border-bottom-right-radius: 4px;\n}\n"], dependencies: [{ kind: "ngmodule", type: CdkAccordionModule }, { kind: "directive", type: i1.CdkAccordion, selector: "cdk-accordion, [cdkAccordion]", inputs: ["multi"], exportAs: ["cdkAccordion"] }, { kind: "directive", type: i1.CdkAccordionItem, selector: "cdk-accordion-item, [cdkAccordionItem]", inputs: ["expanded", "disabled"], outputs: ["closed", "opened", "destroyed", "expandedChange"], exportAs: ["cdkAccordionItem"] }] }); }
}
i0.ɵɵngDeclareClassMetadata({ minVersion: "12.0.0", version: "17.2.0-rc.1", ngImport: i0, type: CdkAccordionOverviewExample, decorators: [{
            type: Component,
            args: [{ selector: 'cdk-accordion-overview-example', standalone: true, imports: [CdkAccordionModule], template: "<cdk-accordion class=\"example-accordion\">\n  @for (item of items; track item; let index = $index) {\n    <cdk-accordion-item\n\n      #accordionItem=\"cdkAccordionItem\"\n      class=\"example-accordion-item\"\n      role=\"button\"\n      tabindex=\"0\"\n      [attr.id]=\"'accordion-header-' + index\"\n      [attr.aria-expanded]=\"accordionItem.expanded\"\n      [attr.aria-controls]=\"'accordion-body-' + index\">\n      <div class=\"example-accordion-item-header\" (click)=\"accordionItem.toggle()\">\n        {{ item }}\n        <span class=\"example-accordion-item-description\">\n          Click to {{ accordionItem.expanded ? 'close' : 'open' }}\n        </span>\n      </div>\n      <div\n        class=\"example-accordion-item-body\"\n        role=\"region\"\n        [style.display]=\"accordionItem.expanded ? '' : 'none'\"\n        [attr.id]=\"'accordion-body-' + index\"\n        [attr.aria-labelledby]=\"'accordion-header-' + index\">\n        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perferendis\n        excepturi incidunt ipsum deleniti labore, tempore non nam doloribus blanditiis\n        veritatis illo autem iure aliquid ullam rem tenetur deserunt velit culpa?\n      </div>\n    </cdk-accordion-item>\n  }\n</cdk-accordion>\n\n", styles: [".example-accordion {\n  display: block;\n  max-width: 500px;\n}\n\n.example-accordion-item {\n  display: block;\n  border: solid 1px #ccc;\n}\n\n.example-accordion-item + .example-accordion-item {\n  border-top: none;\n}\n\n.example-accordion-item-header {\n  display: flex;\n  align-content: center;\n  justify-content: space-between;\n}\n\n.example-accordion-item-description {\n  font-size: 0.85em;\n  color: #999;\n}\n\n.example-accordion-item-header,\n.example-accordion-item-body {\n  padding: 16px;\n}\n\n.example-accordion-item-header:hover {\n  cursor: pointer;\n  background-color: #eee;\n}\n\n.example-accordion-item:first-child {\n  border-top-left-radius: 4px;\n  border-top-right-radius: 4px;\n}\n\n.example-accordion-item:last-child {\n  border-bottom-left-radius: 4px;\n  border-bottom-right-radius: 4px;\n}\n"] }]
        }] });

/**
 * Generated bundle index. Do not edit.
 */

export { CdkAccordionOverviewExample };
//# sourceMappingURL=accordion.mjs.map
