import { FocusMonitorDirectivesExample } from './cdk/a11y/focus-monitor-directives/focus-monitor-directives-example';
import { FocusMonitorFocusViaExample } from './cdk/a11y/focus-monitor-focus-via/focus-monitor-focus-via-example';
import { FocusMonitorOverviewExample } from './cdk/a11y/focus-monitor-overview/focus-monitor-overview-example';
import { CdkDragDropAxisLockExample } from './cdk/drag-drop/cdk-drag-drop-axis-lock/cdk-drag-drop-axis-lock-example';
import { CdkDragDropBoundaryExample } from './cdk/drag-drop/cdk-drag-drop-boundary/cdk-drag-drop-boundary-example';
import { CdkDragDropConnectedSortingGroupExample } from './cdk/drag-drop/cdk-drag-drop-connected-sorting-group/cdk-drag-drop-connected-sorting-group-example';
import { CdkDragDropConnectedSortingExample } from './cdk/drag-drop/cdk-drag-drop-connected-sorting/cdk-drag-drop-connected-sorting-example';
import { CdkDragDropCustomPlaceholderExample } from './cdk/drag-drop/cdk-drag-drop-custom-placeholder/cdk-drag-drop-custom-placeholder-example';
import { CdkDragDropCustomPreviewExample } from './cdk/drag-drop/cdk-drag-drop-custom-preview/cdk-drag-drop-custom-preview-example';
import { CdkDragDropDelayExample } from './cdk/drag-drop/cdk-drag-drop-delay/cdk-drag-drop-delay-example';
import { CdkDragDropDisabledSortingExample } from './cdk/drag-drop/cdk-drag-drop-disabled-sorting/cdk-drag-drop-disabled-sorting-example';
import { CdkDragDropDisabledExample } from './cdk/drag-drop/cdk-drag-drop-disabled/cdk-drag-drop-disabled-example';
import { CdkDragDropEnterPredicateExample } from './cdk/drag-drop/cdk-drag-drop-enter-predicate/cdk-drag-drop-enter-predicate-example';
import { CdkDragDropFreeDragPositionExample } from './cdk/drag-drop/cdk-drag-drop-free-drag-position/cdk-drag-drop-free-drag-position-example';
import { CdkDragDropHandleExample } from './cdk/drag-drop/cdk-drag-drop-handle/cdk-drag-drop-handle-example';
import { CdkDragDropHorizontalSortingExample } from './cdk/drag-drop/cdk-drag-drop-horizontal-sorting/cdk-drag-drop-horizontal-sorting-example';
import { CdkDragDropOverviewExample } from './cdk/drag-drop/cdk-drag-drop-overview/cdk-drag-drop-overview-example';
import { CdkDragDropRootElementExample } from './cdk/drag-drop/cdk-drag-drop-root-element/cdk-drag-drop-root-element-example';
import { CdkDragDropSortingExample } from './cdk/drag-drop/cdk-drag-drop-sorting/cdk-drag-drop-sorting-example';
import { CdkPlatformOverviewExample } from './cdk/platform/cdk-platform-overview/cdk-platform-overview-example';
import { CdkPopoverEditCdkTableFlexExample } from './cdk/popover-edit/cdk-popover-edit-cdk-table-flex/cdk-popover-edit-cdk-table-flex-example';
import { CdkPopoverEditCdkTableExample } from './cdk/popover-edit/cdk-popover-edit-cdk-table/cdk-popover-edit-cdk-table-example';
import { CdkPopoverEditCellSpanVanillaTableExample } from './cdk/popover-edit/cdk-popover-edit-cell-span-vanilla-table/cdk-popover-edit-cell-span-vanilla-table-example';
import { CdkPopoverEditTabOutVanillaTableExample } from './cdk/popover-edit/cdk-popover-edit-tab-out-vanilla-table/cdk-popover-edit-tab-out-vanilla-table-example';
import { CdkPopoverEditVanillaTableExample } from './cdk/popover-edit/cdk-popover-edit-vanilla-table/cdk-popover-edit-vanilla-table-example';
import { ComponentPortalExample, CdkPortalOverviewExample } from './cdk/portal/cdk-portal-overview/cdk-portal-overview-example';
import { CdkVirtualScrollContextExample } from './cdk/scrolling/cdk-virtual-scroll-context/cdk-virtual-scroll-context-example';
import { CdkVirtualScrollCustomStrategyExample } from './cdk/scrolling/cdk-virtual-scroll-custom-strategy/cdk-virtual-scroll-custom-strategy-example';
import { CdkVirtualScrollDataSourceExample } from './cdk/scrolling/cdk-virtual-scroll-data-source/cdk-virtual-scroll-data-source-example';
import { CdkVirtualScrollDlExample } from './cdk/scrolling/cdk-virtual-scroll-dl/cdk-virtual-scroll-dl-example';
import { CdkVirtualScrollFixedBufferExample } from './cdk/scrolling/cdk-virtual-scroll-fixed-buffer/cdk-virtual-scroll-fixed-buffer-example';
import { CdkVirtualScrollHorizontalExample } from './cdk/scrolling/cdk-virtual-scroll-horizontal/cdk-virtual-scroll-horizontal-example';
import { CdkVirtualScrollOverviewExample } from './cdk/scrolling/cdk-virtual-scroll-overview/cdk-virtual-scroll-overview-example';
import { CdkVirtualScrollTemplateCacheExample } from './cdk/scrolling/cdk-virtual-scroll-template-cache/cdk-virtual-scroll-template-cache-example';
import { CustomStepper, CdkCustomStepperWithoutFormExample } from './cdk/stepper/cdk-custom-stepper-without-form/cdk-custom-stepper-without-form-example';
import { CdkTableBasicFlexExample } from './cdk/table/cdk-table-basic-flex/cdk-table-basic-flex-example';
import { CdkTableBasicExample } from './cdk/table/cdk-table-basic/cdk-table-basic-example';
import { TextFieldAutofillDirectiveExample } from './cdk/text-field/text-field-autofill-directive/text-field-autofill-directive-example';
import { TextFieldAutofillMonitorExample } from './cdk/text-field/text-field-autofill-monitor/text-field-autofill-monitor-example';
import { TextFieldAutosizeTextareaExample } from './cdk/text-field/text-field-autosize-textarea/text-field-autosize-textarea-example';
import { CdkTreeFlatExample } from './cdk/tree/cdk-tree-flat/cdk-tree-flat-example';
import { CdkTreeNestedExample } from './cdk/tree/cdk-tree-nested/cdk-tree-nested-example';
import { AutocompleteAutoActiveFirstOptionExample } from './material/autocomplete/autocomplete-auto-active-first-option/autocomplete-auto-active-first-option-example';
import { AutocompleteDisplayExample } from './material/autocomplete/autocomplete-display/autocomplete-display-example';
import { AutocompleteFilterExample } from './material/autocomplete/autocomplete-filter/autocomplete-filter-example';
import { AutocompleteOptgroupExample } from './material/autocomplete/autocomplete-optgroup/autocomplete-optgroup-example';
import { AutocompleteOverviewExample } from './material/autocomplete/autocomplete-overview/autocomplete-overview-example';
import { AutocompletePlainInputExample } from './material/autocomplete/autocomplete-plain-input/autocomplete-plain-input-example';
import { AutocompleteSimpleExample } from './material/autocomplete/autocomplete-simple/autocomplete-simple-example';
import { BadgeOverviewExample } from './material/badge/badge-overview/badge-overview-example';
import { BottomSheetOverviewExampleSheet, BottomSheetOverviewExample } from './material/bottom-sheet/bottom-sheet-overview/bottom-sheet-overview-example';
import { ButtonToggleAppearanceExample } from './material/button-toggle/button-toggle-appearance/button-toggle-appearance-example';
import { ButtonToggleExclusiveExample } from './material/button-toggle/button-toggle-exclusive/button-toggle-exclusive-example';
import { ButtonToggleOverviewExample } from './material/button-toggle/button-toggle-overview/button-toggle-overview-example';
import { ButtonOverviewExample } from './material/button/button-overview/button-overview-example';
import { ButtonTypesExample } from './material/button/button-types/button-types-example';
import { CardFancyExample } from './material/card/card-fancy/card-fancy-example';
import { CardOverviewExample } from './material/card/card-overview/card-overview-example';
import { CheckboxConfigurableExample } from './material/checkbox/checkbox-configurable/checkbox-configurable-example';
import { CheckboxOverviewExample } from './material/checkbox/checkbox-overview/checkbox-overview-example';
import { ChipsAutocompleteExample } from './material/chips/chips-autocomplete/chips-autocomplete-example';
import { ChipsDragDropExample } from './material/chips/chips-drag-and-drop/chips-drag-drop-example';
import { ChipsInputExample } from './material/chips/chips-input/chips-input-example';
import { ChipsOverviewExample } from './material/chips/chips-overview/chips-overview-example';
import { ChipsStackedExample } from './material/chips/chips-stacked/chips-stacked-example';
import { ElevationOverviewExample } from './material/core/elevation-overview/elevation-overview-example';
import { RippleOverviewExample } from './material/core/ripple-overview/ripple-overview-example';
import { DatepickerApiExample } from './material/datepicker/datepicker-api/datepicker-api-example';
import { DatepickerColorExample } from './material/datepicker/datepicker-color/datepicker-color-example';
import { ExampleHeader, DatepickerCustomHeaderExample } from './material/datepicker/datepicker-custom-header/datepicker-custom-header-example';
import { DatepickerCustomIconExample } from './material/datepicker/datepicker-custom-icon/datepicker-custom-icon-example';
import { DatepickerDateClassExample } from './material/datepicker/datepicker-date-class/datepicker-date-class-example';
import { DatepickerDisabledExample } from './material/datepicker/datepicker-disabled/datepicker-disabled-example';
import { DatepickerEventsExample } from './material/datepicker/datepicker-events/datepicker-events-example';
import { DatepickerFilterExample } from './material/datepicker/datepicker-filter/datepicker-filter-example';
import { DatepickerFormatsExample } from './material/datepicker/datepicker-formats/datepicker-formats-example';
import { DatepickerLocaleExample } from './material/datepicker/datepicker-locale/datepicker-locale-example';
import { DatepickerMinMaxExample } from './material/datepicker/datepicker-min-max/datepicker-min-max-example';
import { DatepickerMomentExample } from './material/datepicker/datepicker-moment/datepicker-moment-example';
import { DatepickerOverviewExample } from './material/datepicker/datepicker-overview/datepicker-overview-example';
import { DatepickerStartViewExample } from './material/datepicker/datepicker-start-view/datepicker-start-view-example';
import { DatepickerTouchExample } from './material/datepicker/datepicker-touch/datepicker-touch-example';
import { DatepickerValueExample } from './material/datepicker/datepicker-value/datepicker-value-example';
import { DatepickerViewsSelectionExample } from './material/datepicker/datepicker-views-selection/datepicker-views-selection-example';
import { DialogContentExampleDialog, DialogContentExample } from './material/dialog/dialog-content/dialog-content-example';
import { DialogDataExampleDialog, DialogDataExample } from './material/dialog/dialog-data/dialog-data-example';
import { DialogElementsExampleDialog, DialogElementsExample } from './material/dialog/dialog-elements/dialog-elements-example';
import { DialogOverviewExampleDialog, DialogOverviewExample } from './material/dialog/dialog-overview/dialog-overview-example';
import { DividerOverviewExample } from './material/divider/divider-overview/divider-overview-example';
import { ExpansionExpandCollapseAllExample } from './material/expansion/expansion-expand-collapse-all/expansion-expand-collapse-all-example';
import { ExpansionOverviewExample } from './material/expansion/expansion-overview/expansion-overview-example';
import { ExpansionStepsExample } from './material/expansion/expansion-steps/expansion-steps-example';
import { FormFieldAppearanceExample } from './material/form-field/form-field-appearance/form-field-appearance-example';
import { MyTelInput, FormFieldCustomControlExample } from './material/form-field/form-field-custom-control/form-field-custom-control-example';
import { FormFieldErrorExample } from './material/form-field/form-field-error/form-field-error-example';
import { FormFieldHintExample } from './material/form-field/form-field-hint/form-field-hint-example';
import { FormFieldLabelExample } from './material/form-field/form-field-label/form-field-label-example';
import { FormFieldOverviewExample } from './material/form-field/form-field-overview/form-field-overview-example';
import { FormFieldPrefixSuffixExample } from './material/form-field/form-field-prefix-suffix/form-field-prefix-suffix-example';
import { FormFieldThemingExample } from './material/form-field/form-field-theming/form-field-theming-example';
import { GridListDynamicExample } from './material/grid-list/grid-list-dynamic/grid-list-dynamic-example';
import { GridListOverviewExample } from './material/grid-list/grid-list-overview/grid-list-overview-example';
import { IconOverviewExample } from './material/icon/icon-overview/icon-overview-example';
import { IconSvgExample } from './material/icon/icon-svg/icon-svg-example';
import { InputClearableExample } from './material/input/input-clearable/input-clearable-example';
import { InputErrorStateMatcherExample } from './material/input/input-error-state-matcher/input-error-state-matcher-example';
import { InputErrorsExample } from './material/input/input-errors/input-errors-example';
import { InputFormExample } from './material/input/input-form/input-form-example';
import { InputHintExample } from './material/input/input-hint/input-hint-example';
import { InputOverviewExample } from './material/input/input-overview/input-overview-example';
import { InputPrefixSuffixExample } from './material/input/input-prefix-suffix/input-prefix-suffix-example';
import { ListOverviewExample } from './material/list/list-overview/list-overview-example';
import { ListSectionsExample } from './material/list/list-sections/list-sections-example';
import { ListSelectionExample } from './material/list/list-selection/list-selection-example';
import { MenuIconsExample } from './material/menu/menu-icons/menu-icons-example';
import { MenuOverviewExample } from './material/menu/menu-overview/menu-overview-example';
import { MenuPositionExample } from './material/menu/menu-position/menu-position-example';
import { NestedMenuExample } from './material/menu/nested-menu/nested-menu-example';
import { PaginatorConfigurableExample } from './material/paginator/paginator-configurable/paginator-configurable-example';
import { PaginatorOverviewExample } from './material/paginator/paginator-overview/paginator-overview-example';
import { PopoverEditCellSpanMatTableExample } from './material/popover-edit/popover-edit-cell-span-mat-table/popover-edit-cell-span-mat-table-example';
import { PopoverEditMatTableFlexExample } from './material/popover-edit/popover-edit-mat-table-flex/popover-edit-mat-table-flex-example';
import { PopoverEditMatTableExample } from './material/popover-edit/popover-edit-mat-table/popover-edit-mat-table-example';
import { PopoverEditTabOutMatTableExample } from './material/popover-edit/popover-edit-tab-out-mat-table/popover-edit-tab-out-mat-table-example';
import { ProgressBarBufferExample } from './material/progress-bar/progress-bar-buffer/progress-bar-buffer-example';
import { ProgressBarConfigurableExample } from './material/progress-bar/progress-bar-configurable/progress-bar-configurable-example';
import { ProgressBarDeterminateExample } from './material/progress-bar/progress-bar-determinate/progress-bar-determinate-example';
import { ProgressBarIndeterminateExample } from './material/progress-bar/progress-bar-indeterminate/progress-bar-indeterminate-example';
import { ProgressBarQueryExample } from './material/progress-bar/progress-bar-query/progress-bar-query-example';
import { ProgressSpinnerConfigurableExample } from './material/progress-spinner/progress-spinner-configurable/progress-spinner-configurable-example';
import { ProgressSpinnerOverviewExample } from './material/progress-spinner/progress-spinner-overview/progress-spinner-overview-example';
import { RadioNgModelExample } from './material/radio/radio-ng-model/radio-ng-model-example';
import { RadioOverviewExample } from './material/radio/radio-overview/radio-overview-example';
import { SelectCustomTriggerExample } from './material/select/select-custom-trigger/select-custom-trigger-example';
import { SelectDisabledExample } from './material/select/select-disabled/select-disabled-example';
import { SelectErrorStateMatcherExample } from './material/select/select-error-state-matcher/select-error-state-matcher-example';
import { SelectFormExample } from './material/select/select-form/select-form-example';
import { SelectHintErrorExample } from './material/select/select-hint-error/select-hint-error-example';
import { SelectMultipleExample } from './material/select/select-multiple/select-multiple-example';
import { SelectNoRippleExample } from './material/select/select-no-ripple/select-no-ripple-example';
import { SelectOptgroupExample } from './material/select/select-optgroup/select-optgroup-example';
import { SelectOverviewExample } from './material/select/select-overview/select-overview-example';
import { SelectPanelClassExample } from './material/select/select-panel-class/select-panel-class-example';
import { SelectResetExample } from './material/select/select-reset/select-reset-example';
import { SelectValueBindingExample } from './material/select/select-value-binding/select-value-binding-example';
import { SidenavAutosizeExample } from './material/sidenav/sidenav-autosize/sidenav-autosize-example';
import { SidenavBackdropExample } from './material/sidenav/sidenav-backdrop/sidenav-backdrop-example';
import { SidenavDisableCloseExample } from './material/sidenav/sidenav-disable-close/sidenav-disable-close-example';
import { SidenavDrawerOverviewExample } from './material/sidenav/sidenav-drawer-overview/sidenav-drawer-overview-example';
import { SidenavFixedExample } from './material/sidenav/sidenav-fixed/sidenav-fixed-example';
import { SidenavModeExample } from './material/sidenav/sidenav-mode/sidenav-mode-example';
import { SidenavOpenCloseExample } from './material/sidenav/sidenav-open-close/sidenav-open-close-example';
import { SidenavOverviewExample } from './material/sidenav/sidenav-overview/sidenav-overview-example';
import { SidenavPositionExample } from './material/sidenav/sidenav-position/sidenav-position-example';
import { SidenavResponsiveExample } from './material/sidenav/sidenav-responsive/sidenav-responsive-example';
import { SlideToggleConfigurableExample } from './material/slide-toggle/slide-toggle-configurable/slide-toggle-configurable-example';
import { SlideToggleFormsExample } from './material/slide-toggle/slide-toggle-forms/slide-toggle-forms-example';
import { SlideToggleOverviewExample } from './material/slide-toggle/slide-toggle-overview/slide-toggle-overview-example';
import { SliderConfigurableExample } from './material/slider/slider-configurable/slider-configurable-example';
import { SliderFormattingExample } from './material/slider/slider-formatting/slider-formatting-example';
import { SliderOverviewExample } from './material/slider/slider-overview/slider-overview-example';
import { PizzaPartyComponent, SnackBarComponentExample } from './material/snack-bar/snack-bar-component/snack-bar-component-example';
import { SnackBarOverviewExample } from './material/snack-bar/snack-bar-overview/snack-bar-overview-example';
import { SnackBarPositionExample } from './material/snack-bar/snack-bar-position/snack-bar-position-example';
import { SortOverviewExample } from './material/sort/sort-overview/sort-overview-example';
import { StepperEditableExample } from './material/stepper/stepper-editable/stepper-editable-example';
import { StepperErrorsExample } from './material/stepper/stepper-errors/stepper-errors-example';
import { StepperLabelPositionBottomExample } from './material/stepper/stepper-label-position-bottom/stepper-label-position-bottom-example';
import { StepperOptionalExample } from './material/stepper/stepper-optional/stepper-optional-example';
import { StepperOverviewExample } from './material/stepper/stepper-overview/stepper-overview-example';
import { StepperStatesExample } from './material/stepper/stepper-states/stepper-states-example';
import { StepperVerticalExample } from './material/stepper/stepper-vertical/stepper-vertical-example';
import { TableBasicFlexExample } from './material/table/table-basic-flex/table-basic-flex-example';
import { TableBasicExample } from './material/table/table-basic/table-basic-example';
import { TableDynamicColumnsExample } from './material/table/table-dynamic-columns/table-dynamic-columns-example';
import { TableExpandableRowsExample } from './material/table/table-expandable-rows/table-expandable-rows-example';
import { TableFilteringExample } from './material/table/table-filtering/table-filtering-example';
import { TableFooterRowExample } from './material/table/table-footer-row/table-footer-row-example';
import { TableHttpExample } from './material/table/table-http/table-http-example';
import { TableMultipleHeaderFooterExample } from './material/table/table-multiple-header-footer/table-multiple-header-footer-example';
import { TableOverviewExample } from './material/table/table-overview/table-overview-example';
import { TablePaginationExample } from './material/table/table-pagination/table-pagination-example';
import { TableRowContextExample } from './material/table/table-row-context/table-row-context-example';
import { TableSelectionExample } from './material/table/table-selection/table-selection-example';
import { TableSortingExample } from './material/table/table-sorting/table-sorting-example';
import { TableStickyColumnsExample } from './material/table/table-sticky-columns/table-sticky-columns-example';
import { TableStickyComplexFlexExample } from './material/table/table-sticky-complex-flex/table-sticky-complex-flex-example';
import { TableStickyComplexExample } from './material/table/table-sticky-complex/table-sticky-complex-example';
import { TableStickyFooterExample } from './material/table/table-sticky-footer/table-sticky-footer-example';
import { TableStickyHeaderExample } from './material/table/table-sticky-header/table-sticky-header-example';
import { TableTextColumnAdvancedExample } from './material/table/table-text-column-advanced/table-text-column-advanced-example';
import { TableTextColumnExample } from './material/table/table-text-column/table-text-column-example';
import { WrapperTable, TableWrappedExample } from './material/table/table-wrapped/table-wrapped-example';
import { TabGroupAlignExample } from './material/tabs/tab-group-align/tab-group-align-example';
import { TabGroupAnimationsExample } from './material/tabs/tab-group-animations/tab-group-animations-example';
import { TabGroupAsyncExample } from './material/tabs/tab-group-async/tab-group-async-example';
import { TabGroupBasicExample } from './material/tabs/tab-group-basic/tab-group-basic-example';
import { TabGroupCustomLabelExample } from './material/tabs/tab-group-custom-label/tab-group-custom-label-example';
import { TabGroupDynamicHeightExample } from './material/tabs/tab-group-dynamic-height/tab-group-dynamic-height-example';
import { TabGroupDynamicExample } from './material/tabs/tab-group-dynamic/tab-group-dynamic-example';
import { TabGroupHeaderBelowExample } from './material/tabs/tab-group-header-below/tab-group-header-below-example';
import { TabGroupLazyLoadedExample } from './material/tabs/tab-group-lazy-loaded/tab-group-lazy-loaded-example';
import { TabGroupStretchedExample } from './material/tabs/tab-group-stretched/tab-group-stretched-example';
import { TabGroupThemeExample } from './material/tabs/tab-group-theme/tab-group-theme-example';
import { TabNavBarBasicExample } from './material/tabs/tab-nav-bar-basic/tab-nav-bar-basic-example';
import { ToolbarMultirowExample } from './material/toolbar/toolbar-multirow/toolbar-multirow-example';
import { ToolbarOverviewExample } from './material/toolbar/toolbar-overview/toolbar-overview-example';
import { TooltipAutoHideExample } from './material/tooltip/tooltip-auto-hide/tooltip-auto-hide-example';
import { TooltipCustomClassExample } from './material/tooltip/tooltip-custom-class/tooltip-custom-class-example';
import { TooltipDelayExample } from './material/tooltip/tooltip-delay/tooltip-delay-example';
import { TooltipDisabledExample } from './material/tooltip/tooltip-disabled/tooltip-disabled-example';
import { TooltipManualExample } from './material/tooltip/tooltip-manual/tooltip-manual-example';
import { TooltipMessageExample } from './material/tooltip/tooltip-message/tooltip-message-example';
import { TooltipModifiedDefaultsExample } from './material/tooltip/tooltip-modified-defaults/tooltip-modified-defaults-example';
import { TooltipOverviewExample } from './material/tooltip/tooltip-overview/tooltip-overview-example';
import { TooltipPositionExample } from './material/tooltip/tooltip-position/tooltip-position-example';
import { TreeChecklistExample } from './material/tree/tree-checklist/tree-checklist-example';
import { TreeDynamicExample } from './material/tree/tree-dynamic/tree-dynamic-example';
import { TreeFlatOverviewExample } from './material/tree/tree-flat-overview/tree-flat-overview-example';
import { TreeLoadmoreExample } from './material/tree/tree-loadmore/tree-loadmore-example';
import { TreeNestedOverviewExample } from './material/tree/tree-nested-overview/tree-nested-overview-example';
import { CdkA11yExamplesModule } from './cdk/a11y/module';
export interface LiveExample {
    title: string;
    component: any;
    additionalFiles?: string[];
    selectorName?: string;
}
export declare const EXAMPLE_COMPONENTS: {
    [key: string]: LiveExample;
};
export declare const EXAMPLE_MODULES: (typeof CdkA11yExamplesModule)[];
export declare const EXAMPLE_LIST: (typeof FocusMonitorDirectivesExample | typeof FocusMonitorFocusViaExample | typeof FocusMonitorOverviewExample | typeof CdkDragDropRootElementExample | typeof CdkPlatformOverviewExample | typeof CdkPortalOverviewExample | typeof TextFieldAutofillMonitorExample | typeof TextFieldAutosizeTextareaExample | typeof AutocompleteOptgroupExample | typeof BottomSheetOverviewExample | typeof DatepickerLocaleExample | typeof DialogContentExample | typeof FormFieldLabelExample | typeof IconSvgExample | typeof PopoverEditMatTableExample | typeof SidenavResponsiveExample | typeof SlideToggleFormsExample | typeof SnackBarComponentExample | typeof SnackBarOverviewExample | typeof SnackBarPositionExample | typeof StepperEditableExample | typeof StepperErrorsExample | typeof StepperLabelPositionBottomExample | typeof StepperOptionalExample | typeof StepperOverviewExample | typeof StepperStatesExample | typeof StepperVerticalExample | typeof TableHttpExample | typeof TreeChecklistExample | typeof TreeDynamicExample | typeof TreeLoadmoreExample | typeof CustomStepper | typeof BottomSheetOverviewExampleSheet | typeof ExampleHeader | typeof DialogDataExampleDialog | typeof DialogOverviewExampleDialog | typeof MyTelInput)[];
export declare class ExampleModule {
}
export { FocusMonitorDirectivesExample, FocusMonitorFocusViaExample, FocusMonitorOverviewExample, CdkDragDropAxisLockExample, CdkDragDropBoundaryExample, CdkDragDropConnectedSortingGroupExample, CdkDragDropConnectedSortingExample, CdkDragDropCustomPlaceholderExample, CdkDragDropCustomPreviewExample, CdkDragDropDelayExample, CdkDragDropDisabledSortingExample, CdkDragDropDisabledExample, CdkDragDropEnterPredicateExample, CdkDragDropFreeDragPositionExample, CdkDragDropHandleExample, CdkDragDropHorizontalSortingExample, CdkDragDropOverviewExample, CdkDragDropRootElementExample, CdkDragDropSortingExample, CdkPlatformOverviewExample, CdkPopoverEditCdkTableFlexExample, CdkPopoverEditCdkTableExample, CdkPopoverEditCellSpanVanillaTableExample, CdkPopoverEditTabOutVanillaTableExample, CdkPopoverEditVanillaTableExample, CdkPortalOverviewExample, ComponentPortalExample, CdkVirtualScrollContextExample, CdkVirtualScrollCustomStrategyExample, CdkVirtualScrollDataSourceExample, CdkVirtualScrollDlExample, CdkVirtualScrollFixedBufferExample, CdkVirtualScrollHorizontalExample, CdkVirtualScrollOverviewExample, CdkVirtualScrollTemplateCacheExample, CdkCustomStepperWithoutFormExample, CustomStepper, CdkTableBasicFlexExample, CdkTableBasicExample, TextFieldAutofillDirectiveExample, TextFieldAutofillMonitorExample, TextFieldAutosizeTextareaExample, CdkTreeFlatExample, CdkTreeNestedExample, AutocompleteAutoActiveFirstOptionExample, AutocompleteDisplayExample, AutocompleteFilterExample, AutocompleteOptgroupExample, AutocompleteOverviewExample, AutocompletePlainInputExample, AutocompleteSimpleExample, BadgeOverviewExample, BottomSheetOverviewExample, BottomSheetOverviewExampleSheet, ButtonToggleAppearanceExample, ButtonToggleExclusiveExample, ButtonToggleOverviewExample, ButtonOverviewExample, ButtonTypesExample, CardFancyExample, CardOverviewExample, CheckboxConfigurableExample, CheckboxOverviewExample, ChipsAutocompleteExample, ChipsDragDropExample, ChipsInputExample, ChipsOverviewExample, ChipsStackedExample, ElevationOverviewExample, RippleOverviewExample, DatepickerApiExample, DatepickerColorExample, DatepickerCustomHeaderExample, ExampleHeader, DatepickerCustomIconExample, DatepickerDateClassExample, DatepickerDisabledExample, DatepickerEventsExample, DatepickerFilterExample, DatepickerFormatsExample, DatepickerLocaleExample, DatepickerMinMaxExample, DatepickerMomentExample, DatepickerOverviewExample, DatepickerStartViewExample, DatepickerTouchExample, DatepickerValueExample, DatepickerViewsSelectionExample, DialogContentExample, DialogContentExampleDialog, DialogDataExample, DialogDataExampleDialog, DialogElementsExample, DialogElementsExampleDialog, DialogOverviewExample, DialogOverviewExampleDialog, DividerOverviewExample, ExpansionExpandCollapseAllExample, ExpansionOverviewExample, ExpansionStepsExample, FormFieldAppearanceExample, FormFieldCustomControlExample, MyTelInput, FormFieldErrorExample, FormFieldHintExample, FormFieldLabelExample, FormFieldOverviewExample, FormFieldPrefixSuffixExample, FormFieldThemingExample, GridListDynamicExample, GridListOverviewExample, IconOverviewExample, IconSvgExample, InputClearableExample, InputErrorStateMatcherExample, InputErrorsExample, InputFormExample, InputHintExample, InputOverviewExample, InputPrefixSuffixExample, ListOverviewExample, ListSectionsExample, ListSelectionExample, MenuIconsExample, MenuOverviewExample, MenuPositionExample, NestedMenuExample, PaginatorConfigurableExample, PaginatorOverviewExample, PopoverEditCellSpanMatTableExample, PopoverEditMatTableFlexExample, PopoverEditMatTableExample, PopoverEditTabOutMatTableExample, ProgressBarBufferExample, ProgressBarConfigurableExample, ProgressBarDeterminateExample, ProgressBarIndeterminateExample, ProgressBarQueryExample, ProgressSpinnerConfigurableExample, ProgressSpinnerOverviewExample, RadioNgModelExample, RadioOverviewExample, SelectCustomTriggerExample, SelectDisabledExample, SelectErrorStateMatcherExample, SelectFormExample, SelectHintErrorExample, SelectMultipleExample, SelectNoRippleExample, SelectOptgroupExample, SelectOverviewExample, SelectPanelClassExample, SelectResetExample, SelectValueBindingExample, SidenavAutosizeExample, SidenavBackdropExample, SidenavDisableCloseExample, SidenavDrawerOverviewExample, SidenavFixedExample, SidenavModeExample, SidenavOpenCloseExample, SidenavOverviewExample, SidenavPositionExample, SidenavResponsiveExample, SlideToggleConfigurableExample, SlideToggleFormsExample, SlideToggleOverviewExample, SliderConfigurableExample, SliderFormattingExample, SliderOverviewExample, SnackBarComponentExample, PizzaPartyComponent, SnackBarOverviewExample, SnackBarPositionExample, SortOverviewExample, StepperEditableExample, StepperErrorsExample, StepperLabelPositionBottomExample, StepperOptionalExample, StepperOverviewExample, StepperStatesExample, StepperVerticalExample, TableBasicFlexExample, TableBasicExample, TableDynamicColumnsExample, TableExpandableRowsExample, TableFilteringExample, TableFooterRowExample, TableHttpExample, TableMultipleHeaderFooterExample, TableOverviewExample, TablePaginationExample, TableRowContextExample, TableSelectionExample, TableSortingExample, TableStickyColumnsExample, TableStickyComplexFlexExample, TableStickyComplexExample, TableStickyFooterExample, TableStickyHeaderExample, TableTextColumnAdvancedExample, TableTextColumnExample, TableWrappedExample, WrapperTable, TabGroupAlignExample, TabGroupAnimationsExample, TabGroupAsyncExample, TabGroupBasicExample, TabGroupCustomLabelExample, TabGroupDynamicHeightExample, TabGroupDynamicExample, TabGroupHeaderBelowExample, TabGroupLazyLoadedExample, TabGroupStretchedExample, TabGroupThemeExample, TabNavBarBasicExample, ToolbarMultirowExample, ToolbarOverviewExample, TooltipAutoHideExample, TooltipCustomClassExample, TooltipDelayExample, TooltipDisabledExample, TooltipManualExample, TooltipMessageExample, TooltipModifiedDefaultsExample, TooltipOverviewExample, TooltipPositionExample, TreeChecklistExample, TreeDynamicExample, TreeFlatOverviewExample, TreeLoadmoreExample, TreeNestedOverviewExample };
