import { TabGroupAlignExample } from './tab-group-align/tab-group-align-example';
import { TabGroupAnimationsExample } from './tab-group-animations/tab-group-animations-example';
import { TabGroupAsyncExample } from './tab-group-async/tab-group-async-example';
import { TabGroupBasicExample } from './tab-group-basic/tab-group-basic-example';
import { TabGroupCustomLabelExample } from './tab-group-custom-label/tab-group-custom-label-example';
import { TabGroupDynamicHeightExample } from './tab-group-dynamic-height/tab-group-dynamic-height-example';
import { TabGroupHarnessExample } from './tab-group-harness/tab-group-harness-example';
import { TabGroupDynamicExample } from './tab-group-dynamic/tab-group-dynamic-example';
import { TabGroupHeaderBelowExample } from './tab-group-header-below/tab-group-header-below-example';
import { TabGroupLazyLoadedExample } from './tab-group-lazy-loaded/tab-group-lazy-loaded-example';
import { TabGroupPreserveContentExample } from './tab-group-preserve-content/tab-group-preserve-content-example';
import { TabGroupStretchedExample } from './tab-group-stretched/tab-group-stretched-example';
import { TabGroupThemeExample } from './tab-group-theme/tab-group-theme-example';
import { TabNavBarBasicExample } from './tab-nav-bar-basic/tab-nav-bar-basic-example';
import { TabNavBarWithPanelExample } from './tab-nav-bar-with-panel/tab-nav-bar-with-panel-example';
import * as i0 from "@angular/core";
import * as i1 from "./tab-group-align/tab-group-align-example";
import * as i2 from "./tab-group-animations/tab-group-animations-example";
import * as i3 from "./tab-group-async/tab-group-async-example";
import * as i4 from "./tab-group-basic/tab-group-basic-example";
import * as i5 from "./tab-group-custom-label/tab-group-custom-label-example";
import * as i6 from "./tab-group-dynamic/tab-group-dynamic-example";
import * as i7 from "./tab-group-dynamic-height/tab-group-dynamic-height-example";
import * as i8 from "./tab-group-harness/tab-group-harness-example";
import * as i9 from "./tab-group-header-below/tab-group-header-below-example";
import * as i10 from "./tab-group-lazy-loaded/tab-group-lazy-loaded-example";
import * as i11 from "./tab-group-stretched/tab-group-stretched-example";
import * as i12 from "./tab-group-theme/tab-group-theme-example";
import * as i13 from "./tab-nav-bar-basic/tab-nav-bar-basic-example";
import * as i14 from "./tab-nav-bar-with-panel/tab-nav-bar-with-panel-example";
import * as i15 from "./tab-group-preserve-content/tab-group-preserve-content-example";
import * as i16 from "@angular/common";
import * as i17 from "@angular/material/button";
import * as i18 from "@angular/material/button-toggle";
import * as i19 from "@angular/material/checkbox";
import * as i20 from "@angular/material/icon";
import * as i21 from "@angular/material/input";
import * as i22 from "@angular/material/tabs";
import * as i23 from "@angular/forms";
export { TabGroupAlignExample, TabGroupAnimationsExample, TabGroupAsyncExample, TabGroupBasicExample, TabGroupCustomLabelExample, TabGroupDynamicExample, TabGroupDynamicHeightExample, TabGroupHarnessExample, TabGroupHeaderBelowExample, TabGroupLazyLoadedExample, TabGroupStretchedExample, TabGroupThemeExample, TabNavBarBasicExample, TabNavBarWithPanelExample, TabGroupPreserveContentExample, };
export declare class TabGroupExamplesModule {
    static ɵfac: i0.ɵɵFactoryDeclaration<TabGroupExamplesModule, never>;
    static ɵmod: i0.ɵɵNgModuleDeclaration<TabGroupExamplesModule, [typeof i1.TabGroupAlignExample, typeof i2.TabGroupAnimationsExample, typeof i3.TabGroupAsyncExample, typeof i4.TabGroupBasicExample, typeof i5.TabGroupCustomLabelExample, typeof i6.TabGroupDynamicExample, typeof i7.TabGroupDynamicHeightExample, typeof i8.TabGroupHarnessExample, typeof i9.TabGroupHeaderBelowExample, typeof i10.TabGroupLazyLoadedExample, typeof i11.TabGroupStretchedExample, typeof i12.TabGroupThemeExample, typeof i13.TabNavBarBasicExample, typeof i14.TabNavBarWithPanelExample, typeof i15.TabGroupPreserveContentExample], [typeof i16.CommonModule, typeof i17.MatButtonModule, typeof i18.MatButtonToggleModule, typeof i19.MatCheckboxModule, typeof i20.MatIconModule, typeof i21.MatInputModule, typeof i22.MatTabsModule, typeof i23.ReactiveFormsModule], [typeof i1.TabGroupAlignExample, typeof i2.TabGroupAnimationsExample, typeof i3.TabGroupAsyncExample, typeof i4.TabGroupBasicExample, typeof i5.TabGroupCustomLabelExample, typeof i6.TabGroupDynamicExample, typeof i7.TabGroupDynamicHeightExample, typeof i8.TabGroupHarnessExample, typeof i9.TabGroupHeaderBelowExample, typeof i10.TabGroupLazyLoadedExample, typeof i11.TabGroupStretchedExample, typeof i12.TabGroupThemeExample, typeof i13.TabNavBarBasicExample, typeof i14.TabNavBarWithPanelExample, typeof i15.TabGroupPreserveContentExample]>;
    static ɵinj: i0.ɵɵInjectorDeclaration<TabGroupExamplesModule>;
}
