import { StepperEditableExample } from './stepper-editable/stepper-editable-example';
import { StepperErrorsExample } from './stepper-errors/stepper-errors-example';
import { StepperLabelPositionBottomExample } from './stepper-label-position-bottom/stepper-label-position-bottom-example';
import { StepperOptionalExample } from './stepper-optional/stepper-optional-example';
import { StepperOverviewExample } from './stepper-overview/stepper-overview-example';
import { StepperStatesExample } from './stepper-states/stepper-states-example';
import { StepperVerticalExample } from './stepper-vertical/stepper-vertical-example';
import { StepperHarnessExample } from './stepper-harness/stepper-harness-example';
import { StepperLazyContentExample } from './stepper-lazy-content/stepper-lazy-content-example';
import { StepperResponsiveExample } from './stepper-responsive/stepper-responsive-example';
import * as i0 from "@angular/core";
import * as i1 from "./stepper-editable/stepper-editable-example";
import * as i2 from "./stepper-errors/stepper-errors-example";
import * as i3 from "./stepper-harness/stepper-harness-example";
import * as i4 from "./stepper-label-position-bottom/stepper-label-position-bottom-example";
import * as i5 from "./stepper-optional/stepper-optional-example";
import * as i6 from "./stepper-overview/stepper-overview-example";
import * as i7 from "./stepper-states/stepper-states-example";
import * as i8 from "./stepper-vertical/stepper-vertical-example";
import * as i9 from "./stepper-lazy-content/stepper-lazy-content-example";
import * as i10 from "./stepper-responsive/stepper-responsive-example";
import * as i11 from "@angular/material/button";
import * as i12 from "@angular/material/icon";
import * as i13 from "@angular/material/input";
import * as i14 from "@angular/material/stepper";
import * as i15 from "@angular/forms";
import * as i16 from "@angular/common";
export { StepperEditableExample, StepperErrorsExample, StepperHarnessExample, StepperLabelPositionBottomExample, StepperOptionalExample, StepperOverviewExample, StepperStatesExample, StepperVerticalExample, StepperLazyContentExample, StepperResponsiveExample, };
export declare class StepperExamplesModule {
    static ɵfac: i0.ɵɵFactoryDeclaration<StepperExamplesModule, never>;
    static ɵmod: i0.ɵɵNgModuleDeclaration<StepperExamplesModule, [typeof i1.StepperEditableExample, typeof i2.StepperErrorsExample, typeof i3.StepperHarnessExample, typeof i4.StepperLabelPositionBottomExample, typeof i5.StepperOptionalExample, typeof i6.StepperOverviewExample, typeof i7.StepperStatesExample, typeof i8.StepperVerticalExample, typeof i9.StepperLazyContentExample, typeof i10.StepperResponsiveExample], [typeof i11.MatButtonModule, typeof i12.MatIconModule, typeof i13.MatInputModule, typeof i14.MatStepperModule, typeof i15.ReactiveFormsModule, typeof i16.CommonModule], [typeof i1.StepperEditableExample, typeof i2.StepperErrorsExample, typeof i3.StepperHarnessExample, typeof i4.StepperLabelPositionBottomExample, typeof i5.StepperOptionalExample, typeof i6.StepperOverviewExample, typeof i7.StepperStatesExample, typeof i8.StepperVerticalExample, typeof i9.StepperLazyContentExample, typeof i10.StepperResponsiveExample]>;
    static ɵinj: i0.ɵɵInjectorDeclaration<StepperExamplesModule>;
}
