import { StepperEditableExample } from './stepper-editable/stepper-editable-example';
import { StepperErrorsExample } from './stepper-errors/stepper-errors-example';
import { StepperLabelPositionBottomExample } from './stepper-label-position-bottom/stepper-label-position-bottom-example';
import { StepperOptionalExample } from './stepper-optional/stepper-optional-example';
import { StepperOverviewExample } from './stepper-overview/stepper-overview-example';
import { StepperStatesExample } from './stepper-states/stepper-states-example';
import { StepperVerticalExample } from './stepper-vertical/stepper-vertical-example';
import { StepperHarnessExample } from './stepper-harness/stepper-harness-example';
import { StepperIntlExample } from './stepper-intl/stepper-intl-example';
import { StepperLazyContentExample } from './stepper-lazy-content/stepper-lazy-content-example';
import { StepperResponsiveExample } from './stepper-responsive/stepper-responsive-example';
import { StepperHeaderPositionExample } from './stepper-header-position/stepper-header-position-example';
import { StepperAnimationsExample } from './stepper-animations/stepper-animations-example';
import * as i0 from "@angular/core";
import * as i1 from "./stepper-editable/stepper-editable-example";
import * as i2 from "./stepper-errors/stepper-errors-example";
import * as i3 from "./stepper-harness/stepper-harness-example";
import * as i4 from "./stepper-intl/stepper-intl-example";
import * as i5 from "./stepper-label-position-bottom/stepper-label-position-bottom-example";
import * as i6 from "./stepper-optional/stepper-optional-example";
import * as i7 from "./stepper-overview/stepper-overview-example";
import * as i8 from "./stepper-states/stepper-states-example";
import * as i9 from "./stepper-vertical/stepper-vertical-example";
import * as i10 from "./stepper-lazy-content/stepper-lazy-content-example";
import * as i11 from "./stepper-responsive/stepper-responsive-example";
import * as i12 from "./stepper-header-position/stepper-header-position-example";
import * as i13 from "./stepper-animations/stepper-animations-example";
import * as i14 from "@angular/forms";
import * as i15 from "@angular/material/button";
import * as i16 from "@angular/material/icon";
import * as i17 from "@angular/material/input";
import * as i18 from "@angular/material/radio";
import * as i19 from "@angular/material/stepper";
import * as i20 from "@angular/common";
export { StepperEditableExample, StepperErrorsExample, StepperHarnessExample, StepperIntlExample, StepperLabelPositionBottomExample, StepperOptionalExample, StepperOverviewExample, StepperStatesExample, StepperVerticalExample, StepperLazyContentExample, StepperResponsiveExample, StepperHeaderPositionExample, StepperAnimationsExample, };
export declare class StepperExamplesModule {
    static ɵfac: i0.ɵɵFactoryDeclaration<StepperExamplesModule, never>;
    static ɵmod: i0.ɵɵNgModuleDeclaration<StepperExamplesModule, [typeof i1.StepperEditableExample, typeof i2.StepperErrorsExample, typeof i3.StepperHarnessExample, typeof i4.StepperIntlExample, typeof i5.StepperLabelPositionBottomExample, typeof i6.StepperOptionalExample, typeof i7.StepperOverviewExample, typeof i8.StepperStatesExample, typeof i9.StepperVerticalExample, typeof i10.StepperLazyContentExample, typeof i11.StepperResponsiveExample, typeof i12.StepperHeaderPositionExample, typeof i13.StepperAnimationsExample], [typeof i14.FormsModule, typeof i15.MatButtonModule, typeof i16.MatIconModule, typeof i17.MatInputModule, typeof i18.MatRadioModule, typeof i19.MatStepperModule, typeof i14.ReactiveFormsModule, typeof i20.CommonModule], [typeof i1.StepperEditableExample, typeof i2.StepperErrorsExample, typeof i3.StepperHarnessExample, typeof i4.StepperIntlExample, typeof i5.StepperLabelPositionBottomExample, typeof i6.StepperOptionalExample, typeof i7.StepperOverviewExample, typeof i8.StepperStatesExample, typeof i9.StepperVerticalExample, typeof i10.StepperLazyContentExample, typeof i11.StepperResponsiveExample, typeof i12.StepperHeaderPositionExample, typeof i13.StepperAnimationsExample]>;
    static ɵinj: i0.ɵɵInjectorDeclaration<StepperExamplesModule>;
}
