import { SidenavAutosizeExample } from './sidenav-autosize/sidenav-autosize-example';
import { SidenavBackdropExample } from './sidenav-backdrop/sidenav-backdrop-example';
import { SidenavDisableCloseExample } from './sidenav-disable-close/sidenav-disable-close-example';
import { SidenavDrawerOverviewExample } from './sidenav-drawer-overview/sidenav-drawer-overview-example';
import { SidenavFixedExample } from './sidenav-fixed/sidenav-fixed-example';
import { SidenavModeExample } from './sidenav-mode/sidenav-mode-example';
import { SidenavOpenCloseExample } from './sidenav-open-close/sidenav-open-close-example';
import { SidenavOverviewExample } from './sidenav-overview/sidenav-overview-example';
import { SidenavPositionExample } from './sidenav-position/sidenav-position-example';
import { SidenavResponsiveExample } from './sidenav-responsive/sidenav-responsive-example';
import * as i0 from "@angular/core";
import * as i1 from "./sidenav-autosize/sidenav-autosize-example";
import * as i2 from "./sidenav-backdrop/sidenav-backdrop-example";
import * as i3 from "./sidenav-disable-close/sidenav-disable-close-example";
import * as i4 from "./sidenav-drawer-overview/sidenav-drawer-overview-example";
import * as i5 from "./sidenav-fixed/sidenav-fixed-example";
import * as i6 from "./sidenav-mode/sidenav-mode-example";
import * as i7 from "./sidenav-open-close/sidenav-open-close-example";
import * as i8 from "./sidenav-overview/sidenav-overview-example";
import * as i9 from "./sidenav-position/sidenav-position-example";
import * as i10 from "./sidenav-responsive/sidenav-responsive-example";
import * as i11 from "@angular/common";
import * as i12 from "@angular/forms";
import * as i13 from "@angular/material/button";
import * as i14 from "@angular/material/checkbox";
import * as i15 from "@angular/material/icon";
import * as i16 from "@angular/material/list";
import * as i17 from "@angular/material/radio";
import * as i18 from "@angular/material/sidenav";
import * as i19 from "@angular/material/select";
import * as i20 from "@angular/material/toolbar";
export { SidenavAutosizeExample, SidenavBackdropExample, SidenavDisableCloseExample, SidenavDrawerOverviewExample, SidenavFixedExample, SidenavModeExample, SidenavOpenCloseExample, SidenavOverviewExample, SidenavPositionExample, SidenavResponsiveExample, };
export declare class SidenavExamplesModule {
    static ɵmod: i0.ɵɵNgModuleDefWithMeta<SidenavExamplesModule, [typeof i1.SidenavAutosizeExample, typeof i2.SidenavBackdropExample, typeof i3.SidenavDisableCloseExample, typeof i4.SidenavDrawerOverviewExample, typeof i5.SidenavFixedExample, typeof i6.SidenavModeExample, typeof i7.SidenavOpenCloseExample, typeof i8.SidenavOverviewExample, typeof i9.SidenavPositionExample, typeof i10.SidenavResponsiveExample], [typeof i11.CommonModule, typeof i12.FormsModule, typeof i13.MatButtonModule, typeof i14.MatCheckboxModule, typeof i15.MatIconModule, typeof i16.MatListModule, typeof i17.MatRadioModule, typeof i18.MatSidenavModule, typeof i19.MatSelectModule, typeof i20.MatToolbarModule, typeof i12.ReactiveFormsModule], [typeof i1.SidenavAutosizeExample, typeof i2.SidenavBackdropExample, typeof i3.SidenavDisableCloseExample, typeof i4.SidenavDrawerOverviewExample, typeof i5.SidenavFixedExample, typeof i6.SidenavModeExample, typeof i7.SidenavOpenCloseExample, typeof i8.SidenavOverviewExample, typeof i9.SidenavPositionExample, typeof i10.SidenavResponsiveExample]>;
    static ɵinj: i0.ɵɵInjectorDef<SidenavExamplesModule>;
}
