import { SidenavAutosizeExample } from './sidenav-autosize/sidenav-autosize-example';
import { SidenavBackdropExample } from './sidenav-backdrop/sidenav-backdrop-example';
import { SidenavDisableCloseExample } from './sidenav-disable-close/sidenav-disable-close-example';
import { SidenavDrawerOverviewExample } from './sidenav-drawer-overview/sidenav-drawer-overview-example';
import { SidenavFixedExample } from './sidenav-fixed/sidenav-fixed-example';
import { SidenavModeExample } from './sidenav-mode/sidenav-mode-example';
import { SidenavOpenCloseExample } from './sidenav-open-close/sidenav-open-close-example';
import { SidenavOverviewExample } from './sidenav-overview/sidenav-overview-example';
import { SidenavPositionExample } from './sidenav-position/sidenav-position-example';
import { SidenavResponsiveExample } from './sidenav-responsive/sidenav-responsive-example';
import { SidenavHarnessExample } from './sidenav-harness/sidenav-harness-example';
import * as i0 from "@angular/core";
import * as i1 from "./sidenav-autosize/sidenav-autosize-example";
import * as i2 from "./sidenav-backdrop/sidenav-backdrop-example";
import * as i3 from "./sidenav-disable-close/sidenav-disable-close-example";
import * as i4 from "./sidenav-drawer-overview/sidenav-drawer-overview-example";
import * as i5 from "./sidenav-harness/sidenav-harness-example";
import * as i6 from "./sidenav-fixed/sidenav-fixed-example";
import * as i7 from "./sidenav-mode/sidenav-mode-example";
import * as i8 from "./sidenav-open-close/sidenav-open-close-example";
import * as i9 from "./sidenav-overview/sidenav-overview-example";
import * as i10 from "./sidenav-position/sidenav-position-example";
import * as i11 from "./sidenav-responsive/sidenav-responsive-example";
import * as i12 from "@angular/common";
import * as i13 from "@angular/forms";
import * as i14 from "@angular/material/button";
import * as i15 from "@angular/material/checkbox";
import * as i16 from "@angular/material/icon";
import * as i17 from "@angular/material/list";
import * as i18 from "@angular/material/radio";
import * as i19 from "@angular/material/sidenav";
import * as i20 from "@angular/material/select";
import * as i21 from "@angular/material/toolbar";
export { SidenavAutosizeExample, SidenavBackdropExample, SidenavDisableCloseExample, SidenavDrawerOverviewExample, SidenavHarnessExample, SidenavFixedExample, SidenavModeExample, SidenavOpenCloseExample, SidenavOverviewExample, SidenavPositionExample, SidenavResponsiveExample, };
export declare class SidenavExamplesModule {
    static ɵmod: i0.ɵɵNgModuleDefWithMeta<SidenavExamplesModule, [typeof i1.SidenavAutosizeExample, typeof i2.SidenavBackdropExample, typeof i3.SidenavDisableCloseExample, typeof i4.SidenavDrawerOverviewExample, typeof i5.SidenavHarnessExample, typeof i6.SidenavFixedExample, typeof i7.SidenavModeExample, typeof i8.SidenavOpenCloseExample, typeof i9.SidenavOverviewExample, typeof i10.SidenavPositionExample, typeof i11.SidenavResponsiveExample], [typeof i12.CommonModule, typeof i13.FormsModule, typeof i14.MatButtonModule, typeof i15.MatCheckboxModule, typeof i16.MatIconModule, typeof i17.MatListModule, typeof i18.MatRadioModule, typeof i19.MatSidenavModule, typeof i20.MatSelectModule, typeof i21.MatToolbarModule, typeof i13.ReactiveFormsModule], [typeof i1.SidenavAutosizeExample, typeof i2.SidenavBackdropExample, typeof i3.SidenavDisableCloseExample, typeof i4.SidenavDrawerOverviewExample, typeof i5.SidenavHarnessExample, typeof i6.SidenavFixedExample, typeof i7.SidenavModeExample, typeof i8.SidenavOpenCloseExample, typeof i9.SidenavOverviewExample, typeof i10.SidenavPositionExample, typeof i11.SidenavResponsiveExample]>;
    static ɵinj: i0.ɵɵInjectorDef<SidenavExamplesModule>;
}
