import { FormFieldAppearanceExample } from './form-field-appearance/form-field-appearance-example';
import { FormFieldCustomControlExample, MyTelInput } from './form-field-custom-control/form-field-custom-control-example';
import { FormFieldErrorExample } from './form-field-error/form-field-error-example';
import { FormFieldHintExample } from './form-field-hint/form-field-hint-example';
import { FormFieldLabelExample } from './form-field-label/form-field-label-example';
import { FormFieldOverviewExample } from './form-field-overview/form-field-overview-example';
import { FormFieldPrefixSuffixExample } from './form-field-prefix-suffix/form-field-prefix-suffix-example';
import { FormFieldThemingExample } from './form-field-theming/form-field-theming-example';
import { FormFieldHarnessExample } from './form-field-harness/form-field-harness-example';
import * as i0 from "@angular/core";
import * as i1 from "./form-field-appearance/form-field-appearance-example";
import * as i2 from "./form-field-custom-control/form-field-custom-control-example";
import * as i3 from "./form-field-error/form-field-error-example";
import * as i4 from "./form-field-harness/form-field-harness-example";
import * as i5 from "./form-field-hint/form-field-hint-example";
import * as i6 from "./form-field-label/form-field-label-example";
import * as i7 from "./form-field-overview/form-field-overview-example";
import * as i8 from "./form-field-prefix-suffix/form-field-prefix-suffix-example";
import * as i9 from "./form-field-theming/form-field-theming-example";
import * as i10 from "@angular/common";
import * as i11 from "@angular/material/button";
import * as i12 from "@angular/material/checkbox";
import * as i13 from "@angular/material/form-field";
import * as i14 from "@angular/material/icon";
import * as i15 from "@angular/material/input";
import * as i16 from "@angular/material/radio";
import * as i17 from "@angular/material/select";
import * as i18 from "@angular/forms";
export { FormFieldAppearanceExample, FormFieldCustomControlExample, FormFieldErrorExample, FormFieldHarnessExample, FormFieldHintExample, FormFieldLabelExample, FormFieldOverviewExample, FormFieldPrefixSuffixExample, FormFieldThemingExample, MyTelInput, };
export declare class FormFieldExamplesModule {
    static ɵfac: i0.ɵɵFactoryDef<FormFieldExamplesModule, never>;
    static ɵmod: i0.ɵɵNgModuleDefWithMeta<FormFieldExamplesModule, [typeof i1.FormFieldAppearanceExample, typeof i2.FormFieldCustomControlExample, typeof i3.FormFieldErrorExample, typeof i4.FormFieldHarnessExample, typeof i5.FormFieldHintExample, typeof i6.FormFieldLabelExample, typeof i7.FormFieldOverviewExample, typeof i8.FormFieldPrefixSuffixExample, typeof i9.FormFieldThemingExample, typeof i2.MyTelInput], [typeof i10.CommonModule, typeof i11.MatButtonModule, typeof i12.MatCheckboxModule, typeof i13.MatFormFieldModule, typeof i14.MatIconModule, typeof i15.MatInputModule, typeof i16.MatRadioModule, typeof i17.MatSelectModule, typeof i18.ReactiveFormsModule], [typeof i1.FormFieldAppearanceExample, typeof i2.FormFieldCustomControlExample, typeof i3.FormFieldErrorExample, typeof i4.FormFieldHarnessExample, typeof i5.FormFieldHintExample, typeof i6.FormFieldLabelExample, typeof i7.FormFieldOverviewExample, typeof i8.FormFieldPrefixSuffixExample, typeof i9.FormFieldThemingExample]>;
    static ɵinj: i0.ɵɵInjectorDef<FormFieldExamplesModule>;
}
