import { SelectCustomTriggerExample } from './select-custom-trigger/select-custom-trigger-example';
import { SelectDisabledExample } from './select-disabled/select-disabled-example';
import { SelectErrorStateMatcherExample } from './select-error-state-matcher/select-error-state-matcher-example';
import { SelectFormExample } from './select-form/select-form-example';
import { SelectHintErrorExample } from './select-hint-error/select-hint-error-example';
import { SelectMultipleExample } from './select-multiple/select-multiple-example';
import { SelectNoRippleExample } from './select-no-ripple/select-no-ripple-example';
import { SelectOptgroupExample } from './select-optgroup/select-optgroup-example';
import { SelectOverviewExample } from './select-overview/select-overview-example';
import { SelectPanelClassExample } from './select-panel-class/select-panel-class-example';
import { SelectResetExample } from './select-reset/select-reset-example';
import { SelectValueBindingExample } from './select-value-binding/select-value-binding-example';
import * as i0 from "@angular/core";
import * as i1 from "./select-custom-trigger/select-custom-trigger-example";
import * as i2 from "./select-disabled/select-disabled-example";
import * as i3 from "./select-error-state-matcher/select-error-state-matcher-example";
import * as i4 from "./select-form/select-form-example";
import * as i5 from "./select-hint-error/select-hint-error-example";
import * as i6 from "./select-multiple/select-multiple-example";
import * as i7 from "./select-no-ripple/select-no-ripple-example";
import * as i8 from "./select-optgroup/select-optgroup-example";
import * as i9 from "./select-overview/select-overview-example";
import * as i10 from "./select-panel-class/select-panel-class-example";
import * as i11 from "./select-reset/select-reset-example";
import * as i12 from "./select-value-binding/select-value-binding-example";
import * as i13 from "@angular/common";
import * as i14 from "@angular/forms";
import * as i15 from "@angular/material/checkbox";
import * as i16 from "@angular/material/input";
import * as i17 from "@angular/material/select";
export { SelectCustomTriggerExample, SelectDisabledExample, SelectErrorStateMatcherExample, SelectFormExample, SelectHintErrorExample, SelectMultipleExample, SelectNoRippleExample, SelectOptgroupExample, SelectOverviewExample, SelectPanelClassExample, SelectResetExample, SelectValueBindingExample, };
export declare class SelectExamplesModule {
    static ɵmod: i0.ɵɵNgModuleDefWithMeta<SelectExamplesModule, [typeof i1.SelectCustomTriggerExample, typeof i2.SelectDisabledExample, typeof i3.SelectErrorStateMatcherExample, typeof i4.SelectFormExample, typeof i5.SelectHintErrorExample, typeof i6.SelectMultipleExample, typeof i7.SelectNoRippleExample, typeof i8.SelectOptgroupExample, typeof i9.SelectOverviewExample, typeof i10.SelectPanelClassExample, typeof i11.SelectResetExample, typeof i12.SelectValueBindingExample], [typeof i13.CommonModule, typeof i14.FormsModule, typeof i15.MatCheckboxModule, typeof i16.MatInputModule, typeof i17.MatSelectModule, typeof i14.ReactiveFormsModule], [typeof i1.SelectCustomTriggerExample, typeof i2.SelectDisabledExample, typeof i3.SelectErrorStateMatcherExample, typeof i4.SelectFormExample, typeof i5.SelectHintErrorExample, typeof i6.SelectMultipleExample, typeof i7.SelectNoRippleExample, typeof i8.SelectOptgroupExample, typeof i9.SelectOverviewExample, typeof i10.SelectPanelClassExample, typeof i11.SelectResetExample, typeof i12.SelectValueBindingExample]>;
    static ɵinj: i0.ɵɵInjectorDef<SelectExamplesModule>;
}
