import { SelectCustomTriggerExample } from './select-custom-trigger/select-custom-trigger-example';
import { SelectDisabledExample } from './select-disabled/select-disabled-example';
import { SelectErrorStateMatcherExample } from './select-error-state-matcher/select-error-state-matcher-example';
import { SelectFormExample } from './select-form/select-form-example';
import { SelectHintErrorExample } from './select-hint-error/select-hint-error-example';
import { SelectMultipleExample } from './select-multiple/select-multiple-example';
import { SelectNoRippleExample } from './select-no-ripple/select-no-ripple-example';
import { SelectOptgroupExample } from './select-optgroup/select-optgroup-example';
import { SelectOverviewExample } from './select-overview/select-overview-example';
import { SelectPanelClassExample } from './select-panel-class/select-panel-class-example';
import { SelectResetExample } from './select-reset/select-reset-example';
import { SelectValueBindingExample } from './select-value-binding/select-value-binding-example';
import { SelectReactiveFormExample } from './select-reactive-form/select-reactive-form-example';
import { SelectInitialValueExample } from './select-initial-value/select-initial-value-example';
import { SelectHarnessExample } from './select-harness/select-harness-example';
import * as i0 from "@angular/core";
import * as i1 from "./select-custom-trigger/select-custom-trigger-example";
import * as i2 from "./select-disabled/select-disabled-example";
import * as i3 from "./select-error-state-matcher/select-error-state-matcher-example";
import * as i4 from "./select-form/select-form-example";
import * as i5 from "./select-harness/select-harness-example";
import * as i6 from "./select-hint-error/select-hint-error-example";
import * as i7 from "./select-initial-value/select-initial-value-example";
import * as i8 from "./select-multiple/select-multiple-example";
import * as i9 from "./select-no-ripple/select-no-ripple-example";
import * as i10 from "./select-optgroup/select-optgroup-example";
import * as i11 from "./select-overview/select-overview-example";
import * as i12 from "./select-panel-class/select-panel-class-example";
import * as i13 from "./select-reactive-form/select-reactive-form-example";
import * as i14 from "./select-reset/select-reset-example";
import * as i15 from "./select-value-binding/select-value-binding-example";
import * as i16 from "@angular/common";
import * as i17 from "@angular/forms";
import * as i18 from "@angular/material/checkbox";
import * as i19 from "@angular/material/input";
import * as i20 from "@angular/material/select";
import * as i21 from "@angular/material/form-field";
export { SelectCustomTriggerExample, SelectDisabledExample, SelectErrorStateMatcherExample, SelectFormExample, SelectHarnessExample, SelectHintErrorExample, SelectInitialValueExample, SelectMultipleExample, SelectNoRippleExample, SelectOptgroupExample, SelectOverviewExample, SelectPanelClassExample, SelectReactiveFormExample, SelectResetExample, SelectValueBindingExample, };
export declare class SelectExamplesModule {
    static ɵmod: i0.ɵɵNgModuleDefWithMeta<SelectExamplesModule, [typeof i1.SelectCustomTriggerExample, typeof i2.SelectDisabledExample, typeof i3.SelectErrorStateMatcherExample, typeof i4.SelectFormExample, typeof i5.SelectHarnessExample, typeof i6.SelectHintErrorExample, typeof i7.SelectInitialValueExample, typeof i8.SelectMultipleExample, typeof i9.SelectNoRippleExample, typeof i10.SelectOptgroupExample, typeof i11.SelectOverviewExample, typeof i12.SelectPanelClassExample, typeof i13.SelectReactiveFormExample, typeof i14.SelectResetExample, typeof i15.SelectValueBindingExample], [typeof i16.CommonModule, typeof i17.FormsModule, typeof i18.MatCheckboxModule, typeof i19.MatInputModule, typeof i20.MatSelectModule, typeof i17.ReactiveFormsModule, typeof i21.MatFormFieldModule], [typeof i1.SelectCustomTriggerExample, typeof i2.SelectDisabledExample, typeof i3.SelectErrorStateMatcherExample, typeof i4.SelectFormExample, typeof i5.SelectHarnessExample, typeof i6.SelectHintErrorExample, typeof i7.SelectInitialValueExample, typeof i8.SelectMultipleExample, typeof i9.SelectNoRippleExample, typeof i10.SelectOptgroupExample, typeof i11.SelectOverviewExample, typeof i12.SelectPanelClassExample, typeof i13.SelectReactiveFormExample, typeof i14.SelectResetExample, typeof i15.SelectValueBindingExample]>;
    static ɵinj: i0.ɵɵInjectorDef<SelectExamplesModule>;
}
