import { TooltipAutoHideExample } from './tooltip-auto-hide/tooltip-auto-hide-example';
import { TooltipCustomClassExample } from './tooltip-custom-class/tooltip-custom-class-example';
import { TooltipDelayExample } from './tooltip-delay/tooltip-delay-example';
import { TooltipDisabledExample } from './tooltip-disabled/tooltip-disabled-example';
import { TooltipManualExample } from './tooltip-manual/tooltip-manual-example';
import { TooltipMessageExample } from './tooltip-message/tooltip-message-example';
import { TooltipModifiedDefaultsExample } from './tooltip-modified-defaults/tooltip-modified-defaults-example';
import { TooltipOverviewExample } from './tooltip-overview/tooltip-overview-example';
import { TooltipPositionExample } from './tooltip-position/tooltip-position-example';
import { TooltipHarnessExample } from './tooltip-harness/tooltip-harness-example';
import * as i0 from "@angular/core";
import * as i1 from "./tooltip-auto-hide/tooltip-auto-hide-example";
import * as i2 from "./tooltip-custom-class/tooltip-custom-class-example";
import * as i3 from "./tooltip-delay/tooltip-delay-example";
import * as i4 from "./tooltip-disabled/tooltip-disabled-example";
import * as i5 from "./tooltip-harness/tooltip-harness-example";
import * as i6 from "./tooltip-manual/tooltip-manual-example";
import * as i7 from "./tooltip-message/tooltip-message-example";
import * as i8 from "./tooltip-modified-defaults/tooltip-modified-defaults-example";
import * as i9 from "./tooltip-overview/tooltip-overview-example";
import * as i10 from "./tooltip-position/tooltip-position-example";
import * as i11 from "@angular/common";
import * as i12 from "@angular/material/button";
import * as i13 from "@angular/material/checkbox";
import * as i14 from "@angular/material/input";
import * as i15 from "@angular/material/select";
import * as i16 from "@angular/material/tooltip";
import * as i17 from "@angular/forms";
import * as i18 from "@angular/cdk/scrolling";
export { TooltipAutoHideExample, TooltipCustomClassExample, TooltipDelayExample, TooltipDisabledExample, TooltipHarnessExample, TooltipManualExample, TooltipMessageExample, TooltipModifiedDefaultsExample, TooltipOverviewExample, TooltipPositionExample, };
export declare class TooltipExamplesModule {
    static ɵfac: i0.ɵɵFactoryDeclaration<TooltipExamplesModule, never>;
    static ɵmod: i0.ɵɵNgModuleDeclaration<TooltipExamplesModule, [typeof i1.TooltipAutoHideExample, typeof i2.TooltipCustomClassExample, typeof i3.TooltipDelayExample, typeof i4.TooltipDisabledExample, typeof i5.TooltipHarnessExample, typeof i6.TooltipManualExample, typeof i7.TooltipMessageExample, typeof i8.TooltipModifiedDefaultsExample, typeof i9.TooltipOverviewExample, typeof i10.TooltipPositionExample], [typeof i11.CommonModule, typeof i12.MatButtonModule, typeof i13.MatCheckboxModule, typeof i14.MatInputModule, typeof i15.MatSelectModule, typeof i16.MatTooltipModule, typeof i17.ReactiveFormsModule, typeof i18.ScrollingModule], [typeof i1.TooltipAutoHideExample, typeof i2.TooltipCustomClassExample, typeof i3.TooltipDelayExample, typeof i4.TooltipDisabledExample, typeof i5.TooltipHarnessExample, typeof i6.TooltipManualExample, typeof i7.TooltipMessageExample, typeof i8.TooltipModifiedDefaultsExample, typeof i9.TooltipOverviewExample, typeof i10.TooltipPositionExample]>;
    static ɵinj: i0.ɵɵInjectorDeclaration<TooltipExamplesModule>;
}
